// js/game-editor.js

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function normalizeId(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function prettyJson(value) {
  return JSON.stringify(value, null, 2);
}

function setText(id, value) {
  const el = document.getElementById(id);
  if (!el) return;
  el.textContent = value;
}

function downloadText(filename, text, type = "application/json") {
  const blob = new Blob([text], { type });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();

  setTimeout(() => URL.revokeObjectURL(url), 250);
}

async function copyText(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.warn("Copy failed", error);
    return false;
  }
}

function parseCounters(text) {
  const lines = String(text || "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => !line.startsWith("//") && !line.startsWith("#"));

  const counters = {};

  lines.forEach((line) => {
    const parts = line.split("|").map((part) => part.trim());
    const key = normalizeId(parts[0] || "");
    const label = parts[1] || key;
    const max = Number(parts[2] || 0);
    const icon = parts[3] || "";

    if (!key) return;

    counters[key] = {
      label,
      icon,
      max: Number.isFinite(max) && max > 0 ? max : 0,
      act1: 0
    };
  });

  return counters;
}

function buildGamesJsonEntry(gameId, title) {
  return {
    id: gameId,
    title,
    path: `./data/${gameId}`
  };
}

function buildMetaJson(title, subtitle, difficulty) {
  return {
    title: title || "Untitled Game",
    subtitle: subtitle || "Speedrun Controller",
    difficulty: difficulty || "Default",
    defaultDifficulty: difficulty || "Default"
  };
}

function buildPhasesJson(defaultPhaseId, defaultPhaseLabel, counterKeys) {
  return {
    [defaultPhaseId]: {
      label: defaultPhaseLabel,
      note: "Fallback phase generated by game editor.",
      targetMinutes: 0,
      visible: counterKeys
    }
  };
}

function buildQuotasJson(defaultPhaseId) {
  return {
    [defaultPhaseId]: {}
  };
}

function buildDefaultSplitsJson(defaultPhaseId) {
  return {
    splits: [
      {
        id: "start",
        label: "Start",
        phase: defaultPhaseId,
        note: "Generated starting split.",
        auto: {}
      }
    ]
  };
}

function buildPackage({
  gameId,
  title,
  subtitle,
  difficulty,
  defaultPhaseId,
  defaultPhaseLabel,
  counters
}) {
  const counterKeys = Object.keys(counters);

  return {
    gamesJson: {
      defaultGameId: gameId,
      games: [
        buildGamesJsonEntry(gameId, title)
      ]
    },

    gameEntry: buildGamesJsonEntry(gameId, title),

    metaJson: buildMetaJson(title, subtitle, difficulty),

    countersJson: counters,

    phasesJson: buildPhasesJson(defaultPhaseId, defaultPhaseLabel, counterKeys),

    quotasJson: buildQuotasJson(defaultPhaseId),

    defaultSplitsJson: buildDefaultSplitsJson(defaultPhaseId)
  };
}

function getFormValues() {
  const rawGameId = document.getElementById("gameIdInput")?.value || "";
  const gameId = normalizeId(rawGameId);
  const title = String(document.getElementById("gameTitleInput")?.value || "").trim();
  const subtitle = String(document.getElementById("gameSubtitleInput")?.value || "").trim();
  const difficulty = String(document.getElementById("gameDifficultyInput")?.value || "").trim();
  const defaultPhaseId = normalizeId(document.getElementById("defaultPhaseIdInput")?.value || "legacy_all");
  const defaultPhaseLabel = String(document.getElementById("defaultPhaseLabelInput")?.value || "").trim() || "Legacy All";
  const countersText = document.getElementById("countersInput")?.value || "";

  return {
    gameId,
    title,
    subtitle,
    difficulty,
    defaultPhaseId,
    defaultPhaseLabel,
    counters: parseCounters(countersText)
  };
}

function validateInput(values) {
  if (!values.gameId) {
    throw new Error("Game ID is required.");
  }

  if (!values.title) {
    throw new Error("Game title is required.");
  }

  if (!values.defaultPhaseId) {
    throw new Error("Default phase ID is required.");
  }

  if (!Object.keys(values.counters).length) {
    throw new Error("Add at least one counter.");
  }
}

function renderPackage(pkg) {
  setText("gamesJsonOutput", prettyJson(pkg.gamesJson));
  setText("metaJsonOutput", prettyJson(pkg.metaJson));
  setText("countersJsonOutput", prettyJson(pkg.countersJson));
  setText("phasesJsonOutput", prettyJson(pkg.phasesJson));
  setText("quotasJsonOutput", prettyJson(pkg.quotasJson));
  setText("splitsJsonOutput", prettyJson(pkg.defaultSplitsJson));
}

function buildPackageText(pkg, gameId) {
  return [
    `// games.json entry`,
    prettyJson(pkg.gameEntry),
    ``,
    `// data/${gameId}/meta.json`,
    prettyJson(pkg.metaJson),
    ``,
    `// data/${gameId}/counters.json`,
    prettyJson(pkg.countersJson),
    ``,
    `// data/${gameId}/phases.json`,
    prettyJson(pkg.phasesJson),
    ``,
    `// data/${gameId}/quotas.json`,
    prettyJson(pkg.quotasJson),
    ``,
    `// data/${gameId}/default-splits.json`,
    prettyJson(pkg.defaultSplitsJson)
  ].join("\n");
}

function buildZiplessBundle(pkg, gameId) {
  return {
    "games-entry.json": pkg.gameEntry,
    [`data/${gameId}/meta.json`]: pkg.metaJson,
    [`data/${gameId}/counters.json`]: pkg.countersJson,
    [`data/${gameId}/phases.json`]: pkg.phasesJson,
    [`data/${gameId}/quotas.json`]: pkg.quotasJson,
    [`data/${gameId}/default-splits.json`]: pkg.defaultSplitsJson
  };
}

let currentPackage = null;

function generate() {
  try {
    const values = getFormValues();
    validateInput(values);

    currentPackage = buildPackage(values);
    renderPackage(currentPackage);
  } catch (error) {
    alert(error.message || "Failed to generate scaffold.");
  }
}

function loadExample() {
  const gameIdInput = document.getElementById("gameIdInput");
  const gameTitleInput = document.getElementById("gameTitleInput");
  const gameSubtitleInput = document.getElementById("gameSubtitleInput");
  const gameDifficultyInput = document.getElementById("gameDifficultyInput");
  const defaultPhaseIdInput = document.getElementById("defaultPhaseIdInput");
  const defaultPhaseLabelInput = document.getElementById("defaultPhaseLabelInput");
  const countersInput = document.getElementById("countersInput");

  if (gameIdInput) gameIdInput.value = "ghost-of-tsushima";
  if (gameTitleInput) gameTitleInput.value = "Ghost of Tsushima";
  if (gameSubtitleInput) gameSubtitleInput.value = "Speedrun Controller";
  if (gameDifficultyInput) gameDifficultyInput.value = "Lethal";
  if (defaultPhaseIdInput) defaultPhaseIdInput.value = "legacy_all";
  if (defaultPhaseLabelInput) defaultPhaseLabelInput.value = "Legacy All";

  if (countersInput) {
    countersInput.value = [
      "trophies | Trophies | 52 | 🏆",
      "inari | Inari Shrines | 49 | 🦊",
      "hotsprings | Hot Springs | 18 | ♨️",
      "bamboo | Bamboo Strikes | 16 | 🎋",
      "haiku | Haiku | 19 | 📝",
      "records | Records | 20 | 📜",
      "artifacts | Artifacts | 20 | 🏺",
      "shrines | Shinto Shrines | 16 | ⛩️",
      "lighthouses | Lighthouses | 8 | 🔥",
      "crickets | Crickets | 5 | 🦗",
      "hiddenaltars | Hidden Altars | 10 | 🕯️",
      "duels | Duels | 25 | ⚔️",
      "territories | Mongol Territories | 56 | 🏕️",
      "mythictales | Mythic Tales | 7 | 🌩️",
      "sidetales | Side Tales | 61 | 📖",
      "monochrome | Monochrome | 2 | 🎨",
      "cooper | Cooper | 3 | 🦝"
    ].join("\n");
  }

  generate();
}

function setup() {
  document.getElementById("loadExampleBtn")?.addEventListener("click", loadExample);
  document.getElementById("generateBtn")?.addEventListener("click", generate);

  document.getElementById("copyGamesBtn")?.addEventListener("click", async () => {
    if (!currentPackage) return;
    await copyText(prettyJson(currentPackage.gamesJson));
  });

  document.getElementById("copyPackageBtn")?.addEventListener("click", async () => {
    if (!currentPackage) return;

    const values = getFormValues();
    await copyText(buildPackageText(currentPackage, values.gameId));
  });

  document.getElementById("downloadPackageBtn")?.addEventListener("click", () => {
    if (!currentPackage) return;

    const values = getFormValues();
    const bundle = buildZiplessBundle(currentPackage, values.gameId);

    downloadText(`${values.gameId}-package.json`, prettyJson(bundle));
  });
}

setup();
